MODULE mg_strings
DESCRIPTION IDL bindings for string routines
VERSION 1.0
SOURCE Michael Galloy
BUILD_DATE Thu Feb 24 10:54:00 2011

FUNCTION MG_STREGEX 2 2 KEYWORDS
FUNCTION MG_STRSPLIT 2 2
FUNCTION MG_TRE_VERSION 0 0
FUNCTION MG_TRE_CONFIG 0 0 KEYWORDS
