MODULE mg_zlib
DESCRIPTION IDL bindings for zlib
VERSION 1.0
SOURCE Michael Galloy
BUILD_DATE Thu Feb 22 10:34:00 2013

FUNCTION  MG_ZLIB_VERSION 0 0

PROCEDURE MG_COMPRESS 2 2
PROCEDURE MG_DECOMPRESS 2 2
