unsigned int gsl_ran_bernoulli(unsigned long r, double p);
double gsl_ran_bernoulli_pdf(unsigned int k, double p);
double gsl_ran_beta(unsigned long r, double a, double b);
double gsl_ran_beta_pdf(double x, double a, double b);
unsigned int gsl_ran_binomial(unsigned long r, double p, unsigned int n);
unsigned int gsl_ran_binomial_knuth(unsigned long r, double p, unsigned int n);
unsigned int gsl_ran_binomial_tpe(unsigned long r, double p, unsigned int n);
double gsl_ran_binomial_pdf(unsigned int k, double p, unsigned int n);
double gsl_ran_exponential(unsigned long r, double mu);
double gsl_ran_exponential_pdf(double x, double mu);
double gsl_ran_exppow(unsigned long r, double a, double b);
double gsl_ran_exppow_pdf(double x, double a, double b);
double gsl_ran_cauchy(unsigned long r, double a);
double gsl_ran_cauchy_pdf(double x, double a);
double gsl_ran_chisq(unsigned long r, double nu);
double gsl_ran_chisq_pdf(double x, double nu);
void gsl_ran_dirichlet (unsigned long r, unsigned long K, double alpha[], double theta[]);
double gsl_ran_dirichlet_pdf(unsigned long K, double alpha[], double theta[]);
double gsl_ran_dirichlet_lnpdf(unsigned long K, double alpha[], double theta[]);
double gsl_ran_erlang(unsigned long r, double a, double n);
double gsl_ran_erlang_pdf(double x, double a, double n);
double gsl_ran_fdist(unsigned long r, double nu1, double nu2);
double gsl_ran_fdist_pdf(double x, double nu1, double nu2);
double gsl_ran_flat(unsigned long r, double a, double b);
double gsl_ran_flat_pdf(double x, double a, double b);
double gsl_ran_gamma(unsigned long r, double a, double b);
double gsl_ran_gamma_int(unsigned long r, unsigned int a);
double gsl_ran_gamma_pdf(double x, double a, double b);
double gsl_ran_gamma_mt(unsigned long r, double a, double b);
double gsl_ran_gamma_knuth(unsigned long r, double a, double b);
double gsl_ran_gaussian(unsigned long r, double sigma);
double gsl_ran_gaussian_ratio_method(unsigned long r, double sigma);
double gsl_ran_gaussian_ziggurat(unsigned long r, double sigma);
double gsl_ran_gaussian_pdf(double x, double sigma);
double gsl_ran_ugaussian(unsigned long r);
double gsl_ran_ugaussian_ratio_method(unsigned long r);
double gsl_ran_ugaussian_pdf(double x);
double gsl_ran_gaussian_tail(unsigned long r, double a, double sigma);
double gsl_ran_gaussian_tail_pdf(double x, double a, double sigma);
double gsl_ran_ugaussian_tail(unsigned long r, double a);
double gsl_ran_ugaussian_tail_pdf(double x, double a);
void gsl_ran_bivariate_gaussian(unsigned long r, double sigma_x, double sigma_y, double rho, double *x, double *y);
double gsl_ran_bivariate_gaussian_pdf(double x, double y, double sigma_x, double sigma_y, double rho);
double gsl_ran_landau(unsigned long r);
double gsl_ran_landau_pdf(double x);
unsigned int gsl_ran_geometric(unsigned long r, double p);
double gsl_ran_geometric_pdf(unsigned int k, double p);
unsigned int gsl_ran_hypergeometric(unsigned long r, unsigned int n1, unsigned int n2, unsigned int t);
double gsl_ran_hypergeometric_pdf(unsigned int k, unsigned int n1, unsigned int n2, unsigned int t);
double gsl_ran_gumbel1(unsigned long r, double a, double b);
double gsl_ran_gumbel1_pdf(double x, double a, double b);
double gsl_ran_gumbel2(unsigned long r, double a, double b);
double gsl_ran_gumbel2_pdf(double x, double a, double b);
double gsl_ran_logistic(unsigned long r, double a);
double gsl_ran_logistic_pdf(double x, double a);
double gsl_ran_lognormal(unsigned long r, double zeta, double sigma);
double gsl_ran_lognormal_pdf(double x, double zeta, double sigma);
unsigned int gsl_ran_logarithmic(unsigned long r, double p);
double gsl_ran_logarithmic_pdf(unsigned int k, double p);
void gsl_ran_multinomial(unsigned long r, unsigned long K, unsigned int N, double p[], unsigned int n[] );
double gsl_ran_multinomial_pdf(unsigned long K, double p[], unsigned int n[]);
double gsl_ran_multinomial_lnpdf(unsigned long K, double p[], unsigned int n[]);
unsigned int gsl_ran_negative_binomial(unsigned long r, double p, double n);
double gsl_ran_negative_binomial_pdf(unsigned int k, double p, double n);
unsigned int gsl_ran_pascal(unsigned long r, double p, unsigned int n);
double gsl_ran_pascal_pdf (unsigned int k, double p, unsigned int n);
double gsl_ran_pareto(unsigned long r, double a, double b);
double gsl_ran_pareto_pdf(double x, double a, double b);
unsigned int gsl_ran_poisson (unsigned long r, double mu);
void gsl_ran_poisson_array(unsigned long r, unsigned long n, unsigned int array[], double mu);
double gsl_ran_poisson_pdf( unsigned int k, double mu);
double gsl_ran_rayleigh(unsigned long r, double sigma);
double gsl_ran_rayleigh_pdf(double x, double sigma);
double gsl_ran_rayleigh_tail(unsigned long r, double a, double sigma);
double gsl_ran_rayleigh_tail_pdf(double x, double a, double sigma);
double gsl_ran_tdist(unsigned long r, double nu);
double gsl_ran_tdist_pdf(double x, double nu);
double gsl_ran_laplace(unsigned long r, double a);
double gsl_ran_laplace_pdf(double x, double a);
double gsl_ran_levy(unsigned long r, double c, double alpha);
double gsl_ran_levy_skew(unsigned long r, double c, double alpha, double beta);
double gsl_ran_weibull(unsigned long r, double a, double b);
double gsl_ran_weibull_pdf(double x, double a, double b);
