unsigned int gsl_ran_bernoulli(IDL_PTRINT r, double p);
double gsl_ran_bernoulli_pdf(unsigned int k, double p);
double gsl_ran_beta(IDL_PTRINT r, double a, double b);
double gsl_ran_beta_pdf(double x, double a, double b);
unsigned int gsl_ran_binomial(IDL_PTRINT r, double p, unsigned int n);
unsigned int gsl_ran_binomial_knuth(IDL_PTRINT r, double p, unsigned int n);
unsigned int gsl_ran_binomial_tpe(IDL_PTRINT r, double p, unsigned int n);
double gsl_ran_binomial_pdf(unsigned int k, double p, unsigned int n);
double gsl_ran_exponential(IDL_PTRINT r, double mu);
double gsl_ran_exponential_pdf(double x, double mu);
double gsl_ran_exppow(IDL_PTRINT r, double a, double b);
double gsl_ran_exppow_pdf(double x, double a, double b);
double gsl_ran_cauchy(IDL_PTRINT r, double a);
double gsl_ran_cauchy_pdf(double x, double a);
double gsl_ran_chisq(IDL_PTRINT r, double nu);
double gsl_ran_chisq_pdf(double x, double nu);
void gsl_ran_dirichlet (IDL_PTRINT r, unsigned long K, double alpha[], double theta[]);
double gsl_ran_dirichlet_pdf(unsigned long K, double alpha[], double theta[]);
double gsl_ran_dirichlet_lnpdf(unsigned long K, double alpha[], double theta[]);
double gsl_ran_erlang(IDL_PTRINT r, double a, double n);
double gsl_ran_erlang_pdf(double x, double a, double n);
double gsl_ran_fdist(IDL_PTRINT r, double nu1, double nu2);
double gsl_ran_fdist_pdf(double x, double nu1, double nu2);
double gsl_ran_flat(IDL_PTRINT r, double a, double b);
double gsl_ran_flat_pdf(double x, double a, double b);
double gsl_ran_gamma(IDL_PTRINT r, double a, double b);
double gsl_ran_gamma_int(IDL_PTRINT r, unsigned int a);
double gsl_ran_gamma_pdf(double x, double a, double b);
double gsl_ran_gamma_mt(IDL_PTRINT r, double a, double b);
double gsl_ran_gamma_knuth(IDL_PTRINT r, double a, double b);
double gsl_ran_gaussian(IDL_PTRINT r, double sigma);
double gsl_ran_gaussian_ratio_method(IDL_PTRINT r, double sigma);
double gsl_ran_gaussian_ziggurat(IDL_PTRINT r, double sigma);
double gsl_ran_gaussian_pdf(double x, double sigma);
double gsl_ran_ugaussian(IDL_PTRINT r);
double gsl_ran_ugaussian_ratio_method(IDL_PTRINT r);
double gsl_ran_ugaussian_pdf(double x);
double gsl_ran_gaussian_tail(IDL_PTRINT r, double a, double sigma);
double gsl_ran_gaussian_tail_pdf(double x, double a, double sigma);
double gsl_ran_ugaussian_tail(IDL_PTRINT r, double a);
double gsl_ran_ugaussian_tail_pdf(double x, double a);
void gsl_ran_bivariate_gaussian(IDL_PTRINT r, double sigma_x, double sigma_y, double rho, double *x, double *y);
double gsl_ran_bivariate_gaussian_pdf(double x, double y, double sigma_x, double sigma_y, double rho);
double gsl_ran_landau(IDL_PTRINT r);
double gsl_ran_landau_pdf(double x);
unsigned int gsl_ran_geometric(IDL_PTRINT r, double p);
double gsl_ran_geometric_pdf(unsigned int k, double p);
unsigned int gsl_ran_hypergeometric(IDL_PTRINT r, unsigned int n1, unsigned int n2, unsigned int t);
double gsl_ran_hypergeometric_pdf(unsigned int k, unsigned int n1, unsigned int n2, unsigned int t);
double gsl_ran_gumbel1(IDL_PTRINT r, double a, double b);
double gsl_ran_gumbel1_pdf(double x, double a, double b);
double gsl_ran_gumbel2(IDL_PTRINT r, double a, double b);
double gsl_ran_gumbel2_pdf(double x, double a, double b);
double gsl_ran_logistic(IDL_PTRINT r, double a);
double gsl_ran_logistic_pdf(double x, double a);
double gsl_ran_lognormal(IDL_PTRINT r, double zeta, double sigma);
double gsl_ran_lognormal_pdf(double x, double zeta, double sigma);
unsigned int gsl_ran_logarithmic(IDL_PTRINT r, double p);
double gsl_ran_logarithmic_pdf(unsigned int k, double p);
void gsl_ran_multinomial(IDL_PTRINT r, unsigned long K, unsigned int N, double p[], unsigned int n[] );
double gsl_ran_multinomial_pdf(unsigned long K, double p[], unsigned int n[]);
double gsl_ran_multinomial_lnpdf(unsigned long K, double p[], unsigned int n[]);
unsigned int gsl_ran_negative_binomial(IDL_PTRINT r, double p, double n);
double gsl_ran_negative_binomial_pdf(unsigned int k, double p, double n);
unsigned int gsl_ran_pascal(IDL_PTRINT r, double p, unsigned int n);
double gsl_ran_pascal_pdf (unsigned int k, double p, unsigned int n);
double gsl_ran_pareto(IDL_PTRINT r, double a, double b);
double gsl_ran_pareto_pdf(double x, double a, double b);
unsigned int gsl_ran_poisson (IDL_PTRINT r, double mu);
void gsl_ran_poisson_array(IDL_PTRINT r, unsigned long n, unsigned int array[], double mu);
double gsl_ran_poisson_pdf( unsigned int k, double mu);
double gsl_ran_rayleigh(IDL_PTRINT r, double sigma);
double gsl_ran_rayleigh_pdf(double x, double sigma);
double gsl_ran_rayleigh_tail(IDL_PTRINT r, double a, double sigma);
double gsl_ran_rayleigh_tail_pdf(double x, double a, double sigma);
double gsl_ran_tdist(IDL_PTRINT r, double nu);
double gsl_ran_tdist_pdf(double x, double nu);
double gsl_ran_laplace(IDL_PTRINT r, double a);
double gsl_ran_laplace_pdf(double x, double a);
double gsl_ran_levy(IDL_PTRINT r, double c, double alpha);
double gsl_ran_levy_skew(IDL_PTRINT r, double c, double alpha, double beta);
double gsl_ran_weibull(IDL_PTRINT r, double a, double b);
double gsl_ran_weibull_pdf(double x, double a, double b);
