int culaCgemm(char transa, char transb, int m, int n, int k, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX b[], int ldb, IDL_COMPLEX beta, IDL_COMPLEX c[], int ldc);
int culaCgemv(char trans, int m, int n, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX x[], int incx, IDL_COMPLEX beta, IDL_COMPLEX y[], int incy);
int culaChemm(char side, char uplo, int m, int n, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX b[], int ldb, IDL_COMPLEX beta, IDL_COMPLEX c[], int ldc);
int culaChemv(char uplo, int n, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX x[], int incx, IDL_COMPLEX beta, IDL_COMPLEX y[], int incy);
int culaCher2k(char uplo, char trans, int n, int k, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX b[], int ldb, float beta, IDL_COMPLEX c[], int ldc);
int culaCherk(char uplo, char trans, int n, int k, float alpha, IDL_COMPLEX a[], int lda, float beta, IDL_COMPLEX c[], int ldc);
int culaCsymm(char side, char uplo, int m, int n, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX b[], int ldb, IDL_COMPLEX beta, IDL_COMPLEX c[], int ldc);
int culaCsyr2k(char uplo, char trans, int n, int k, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX b[], int ldb, IDL_COMPLEX beta, IDL_COMPLEX c[], int ldc);
int culaCsyrk(char uplo, char trans, int n, int k, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX beta, IDL_COMPLEX c[], int ldc);
int culaCtrmm(char side, char uplo, char transa, char diag, int m, int n, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX b[], int ldb);
int culaCtrsm(char side, char uplo, char transa, char diag, int m, int n, IDL_COMPLEX alpha, IDL_COMPLEX a[], int lda, IDL_COMPLEX b[], int ldb);
int culaDgemm(char transa, char transb, int m, int n, int k, double alpha, double a[], int lda, double b[], int ldb, double beta, double c[], int ldc);
int culaDgemv(char trans, int m, int n, double alpha, double a[], int lda, double x[], int incx, double beta, double y[], int incy);
int culaDsymm(char side, char uplo, int m, int n, double alpha, double a[], int lda, double b[], int ldb, double beta, double c[], int ldc);
int culaDsymv(char uplo, int n, double alpha, double a[], int lda, double x[], int incx, double beta, double y[], int incy);
int culaDsyr2k(char uplo, char trans, int n, int k, double alpha, double a[], int lda, double b[], int ldb, double beta, double c[], int ldc);
int culaDsyrk(char uplo, char trans, int n, int k, double alpha, double a[], int lda, double beta, double c[], int ldc);
int culaDtrmm(char side, char uplo, char transa, char diag, int m, int n, double alpha, double a[], int lda, double b[], int ldb);
int culaDtrsm(char side, char uplo, char transa, char diag, int m, int n, double alpha, double a[], int lda, double b[], int ldb);
int culaSgemm(char transa, char transb, int m, int n, int k, float alpha, float a[], int lda, float b[], int ldb, float beta, float c[], int ldc);
int culaSgemv(char trans, int m, int n, float alpha, float a[], int lda, float x[], int incx, float beta, float y[], int incy);
int culaSsymm(char side, char uplo, int m, int n, float alpha, float a[], int lda, float b[], int ldb, float beta, float c[], int ldc);
int culaSsymv(char uplo, int n, float alpha, float a[], int lda, float x[], int incx, float beta, float y[], int incy);
int culaSsyr2k(char uplo, char trans, int n, int k, float alpha, float a[], int lda, float b[], int ldb, float beta, float c[], int ldc);
int culaSsyrk(char uplo, char trans, int n, int k, float alpha, float a[], int lda, float beta, float c[], int ldc);
int culaStrmm(char side, char uplo, char transa, char diag, int m, int n, float alpha, float a[], int lda, float b[], int ldb);
int culaStrsm(char side, char uplo, char transa, char diag, int m, int n, float alpha, float a[], int lda, float b[], int ldb);
int culaZgemm(char transa, char transb, int m, int n, int k, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX b[], int ldb, IDL_DCOMPLEX beta, IDL_DCOMPLEX c[], int ldc);
int culaZgemv(char trans, int m, int n, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX x[], int incx, IDL_DCOMPLEX beta, IDL_DCOMPLEX y[], int incy);
int culaZhemm(char side, char uplo, int m, int n, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX b[], int ldb, IDL_DCOMPLEX beta, IDL_DCOMPLEX c[], int ldc);
int culaZhemv(char uplo, int n, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX x[], int incx, IDL_DCOMPLEX beta, IDL_DCOMPLEX y[], int incy);
int culaZher2k(char uplo, char trans, int n, int k, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX b[], int ldb, double beta, IDL_DCOMPLEX c[], int ldc);
int culaZherk(char uplo, char trans, int n, int k, double alpha, IDL_DCOMPLEX a[], int lda, double beta, IDL_DCOMPLEX c[], int ldc);
int culaZsymm(char side, char uplo, int m, int n, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX b[], int ldb, IDL_DCOMPLEX beta, IDL_DCOMPLEX c[], int ldc);
int culaZsyr2k(char uplo, char trans, int n, int k, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX b[], int ldb, IDL_DCOMPLEX beta, IDL_DCOMPLEX c[], int ldc);
int culaZsyrk(char uplo, char trans, int n, int k, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX beta, IDL_DCOMPLEX c[], int ldc);
int culaZtrmm(char side, char uplo, char transa, char diag, int m, int n, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX b[], int ldb);
int culaZtrsm(char side, char uplo, char transa, char diag, int m, int n, IDL_DCOMPLEX alpha, IDL_DCOMPLEX a[], int lda, IDL_DCOMPLEX b[], int ldb);
