MODULE mg_cmdline_tools
DESCRIPTION Tools for the command line
VERSION 1.2
SOURCE mgalloy
BUILD_DATE March 6, 2009
FUNCTION   MG_TERMLINES   0 0
FUNCTION   MG_TERMCOLUMNS 0 0
FUNCTION   MG_TERMISTTY   0 0
PROCEDURE  MG_PRINT       0 IDL_MAXPARAMS KEYWORDS
FUNCTION   MG_HEAPID      1 1
