MODULE mg_dist_tools
DESCRIPTION Tools for the distributing IDL packages
VERSION 1.0
SOURCE mgalloy
BUILD_DATE June 2, 2009
FUNCTION MG_LOGINNAME  0 0
FUNCTION MG_HOMEDIR    0 0
FUNCTION MG_PID        0 0
FUNCTION MG_HOSTNAME   0 0
